version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:5
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  app:
    container_name: app
    depends_on:
      - mongo
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - PORT = 3000 
      - MONGODB_URL = mongodb://mongo:27017
      - DB_NAME = loginDB
    stdin_open: true
    tty: true
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  db:
  caddy_data:
  caddy_config: